# Generated by Django 4.2 on 2023-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
